graph_less=True
# spec_in=2*graph.num_classes
# spec_out= graph.num_classes
num_linear = 2
add_relu = True
conv1_out = 128
conv1_out_dim = conv1_out
conv2_out = conv2_out
conv_bias=True
p_dropout=0.5
